In [1]:
# Supress Warnings

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Importing Pandas and NumPy
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("kag_risk_factors_cervical_cancer.csv")
df.head()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,?,?,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,?,?,0,0,0,0,0,0,0,0
2,34,1.0,?,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,?,?,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,0.0,...,?,?,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,...,?,?,0,0,0,0,0,0,0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 858 entries, 0 to 857
Data columns (total 36 columns):
Age                                   858 non-null int64
Number of sexual partners             858 non-null object
First sexual intercourse              858 non-null object
Num of pregnancies                    858 non-null object
Smokes                                858 non-null object
Smokes (years)                        858 non-null object
Smokes (packs/year)                   858 non-null object
Hormonal Contraceptives               858 non-null object
Hormonal Contraceptives (years)       858 non-null object
IUD                                   858 non-null object
IUD (years)                           858 non-null object
STDs                                  858 non-null object
STDs (number)                         858 non-null object
STDs:condylomatosis                   858 non-null object
STDs:cervical condylomatosis          858 non-null object
STDs:vaginal condylomatosis           858 non-null object
STDs:vulvo-perineal condylomatosis    858 non-null object
STDs:syphilis                         858 non-null object
STDs:pelvic inflammatory disease      858 non-null object
STDs:genital herpes                   858 non-null object
STDs:molluscum contagiosum            858 non-null object
STDs:AIDS                             858 non-null object
STDs:HIV                              858 non-null object
STDs:Hepatitis B                      858 non-null object
STDs:HPV                              858 non-null object
STDs: Number of diagnosis             858 non-null int64
STDs: Time since first diagnosis      858 non-null object
STDs: Time since last diagnosis       858 non-null object
Dx:Cancer                             858 non-null int64
Dx:CIN                                858 non-null int64
Dx:HPV                                858 non-null int64
Dx                                    858 non-null int64
Hinselmann                            858 non-null int64
Schiller                              858 non-null int64
Citology                              858 non-null int64
Biopsy                                858 non-null int64
dtypes: int64(10), object(26)
memory usage: 241.4+ KB

In [5]:
#as  you can see there are ?  values in some column  replace them by nan
df=df.replace('?', np.nan)

In [6]:
#lets count nan values in each  column
# Checking the percentage of missing values
round(100*(df.isnull().sum()/len(df.index)), 2)

Age                                    0.00
Number of sexual partners              3.03
First sexual intercourse               0.82
Num of pregnancies                     6.53
Smokes                                 1.52
Smokes (years)                         1.52
Smokes (packs/year)                    1.52
Hormonal Contraceptives               12.59
Hormonal Contraceptives (years)       12.59
IUD                                   13.64
IUD (years)                           13.64
STDs                                  12.24
STDs (number)                         12.24
STDs:condylomatosis                   12.24
STDs:cervical condylomatosis          12.24
STDs:vaginal condylomatosis           12.24
STDs:vulvo-perineal condylomatosis    12.24
STDs:syphilis                         12.24
STDs:pelvic inflammatory disease      12.24
STDs:genital herpes                   12.24
STDs:molluscum contagiosum            12.24
STDs:AIDS                             12.24
STDs:HIV                              12.24
STDs:Hepatitis B                      12.24
STDs:HPV                              12.24
STDs: Number of diagnosis              0.00
STDs: Time since first diagnosis      91.72
STDs: Time since last diagnosis       91.72
Dx:Cancer                              0.00
Dx:CIN                                 0.00
Dx:HPV                                 0.00
Dx                                     0.00
Hinselmann                             0.00
Schiller                               0.00
Citology                               0.00
Biopsy                                 0.00
dtype: float64

In [7]:
df=df.rename(columns={'STDs: Time since first diagnosis':'STDs:_Time_since_first_diagnosis', 'STDs: Time since last diagnosis':'STDs:_Time_since_last_diagnosis'})

In [8]:
df.drop(['STDs:_Time_since_first_diagnosis','STDs:_Time_since_last_diagnosis'], axis=1, inplace=True)

In [9]:
#lets count nan values in each  column
# Checking the percentage of missing values
round(100*(df.isnull().sum()/len(df.index)), 2)

Age                                    0.00
Number of sexual partners              3.03
First sexual intercourse               0.82
Num of pregnancies                     6.53
Smokes                                 1.52
Smokes (years)                         1.52
Smokes (packs/year)                    1.52
Hormonal Contraceptives               12.59
Hormonal Contraceptives (years)       12.59
IUD                                   13.64
IUD (years)                           13.64
STDs                                  12.24
STDs (number)                         12.24
STDs:condylomatosis                   12.24
STDs:cervical condylomatosis          12.24
STDs:vaginal condylomatosis           12.24
STDs:vulvo-perineal condylomatosis    12.24
STDs:syphilis                         12.24
STDs:pelvic inflammatory disease      12.24
STDs:genital herpes                   12.24
STDs:molluscum contagiosum            12.24
STDs:AIDS                             12.24
STDs:HIV                              12.24
STDs:Hepatitis B                      12.24
STDs:HPV                              12.24
STDs: Number of diagnosis              0.00
Dx:Cancer                              0.00
Dx:CIN                                 0.00
Dx:HPV                                 0.00
Dx                                     0.00
Hinselmann                             0.00
Schiller                               0.00
Citology                               0.00
Biopsy                                 0.00
dtype: float64

In [10]:
df.Biopsy.value_counts()

0    803
1     55
Name: Biopsy, dtype: int64

In [11]:
df=df.rename(columns={'Number of sexual partners':'Number_of_sexual_partners', 'First sexual intercourse':'First_sexual_intercourse'})

In [12]:
df.Number_of_sexual_partners.value_counts()

2.0     272
3.0     208
1.0     206
4.0      78
5.0      44
6.0       9
7.0       7
8.0       4
15.0      1
9.0       1
10.0      1
28.0      1
Name: Number_of_sexual_partners, dtype: int64

In [13]:
#replace nan with either  higher count or unknown
df['Number_of_sexual_partners']=df['Number_of_sexual_partners'].fillna(2.0)
#df['payer_code']=df['payer_code'].fillna('Unknown')
#df['medical_specialty']=df['medical_specialty'].fillna('Unknown')

In [14]:
df.Number_of_sexual_partners.value_counts()

2.0     272
3.0     208
1.0     206
4.0      78
5.0      44
2.0      26
6.0       9
7.0       7
8.0       4
15.0      1
9.0       1
10.0      1
28.0      1
Name: Number_of_sexual_partners, dtype: int64

In [15]:
df = df[df['First_sexual_intercourse'].notnull()]

In [16]:
#lets count nan values in each  column
# Checking the percentage of missing values
round(100*(df.isnull().sum()/len(df.index)), 2)

Age                                    0.00
Number_of_sexual_partners              0.00
First_sexual_intercourse               0.00
Num of pregnancies                     6.58
Smokes                                 1.53
Smokes (years)                         1.53
Smokes (packs/year)                    1.53
Hormonal Contraceptives               12.57
Hormonal Contraceptives (years)       12.57
IUD                                   13.63
IUD (years)                           13.63
STDs                                  12.22
STDs (number)                         12.22
STDs:condylomatosis                   12.22
STDs:cervical condylomatosis          12.22
STDs:vaginal condylomatosis           12.22
STDs:vulvo-perineal condylomatosis    12.22
STDs:syphilis                         12.22
STDs:pelvic inflammatory disease      12.22
STDs:genital herpes                   12.22
STDs:molluscum contagiosum            12.22
STDs:AIDS                             12.22
STDs:HIV                              12.22
STDs:Hepatitis B                      12.22
STDs:HPV                              12.22
STDs: Number of diagnosis              0.00
Dx:Cancer                              0.00
Dx:CIN                                 0.00
Dx:HPV                                 0.00
Dx                                     0.00
Hinselmann                             0.00
Schiller                               0.00
Citology                               0.00
Biopsy                                 0.00
dtype: float64

In [17]:
df.reset_index(drop=True, inplace=True)

In [19]:
df.Smokes.value_counts()

0.0    716
1.0    122
Name: Smokes, dtype: int64

In [21]:
df=df.rename(columns={'Num of pregnancies':'Num_of_pregnancies', 'Smokes (years) ':'Smokes_yr','Smokes (packs/year)':'Smo_pks/yr'})

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851 entries, 0 to 850
Data columns (total 34 columns):
Age                                   851 non-null int64
Number_of_sexual_partners             851 non-null object
First_sexual_intercourse              851 non-null object
Num_of_pregnancies                    795 non-null object
Smokes                                838 non-null object
Smokes (years)                        838 non-null object
Smo_pks/yr                            838 non-null object
Hormonal Contraceptives               744 non-null object
Hormonal Contraceptives (years)       744 non-null object
IUD                                   735 non-null object
IUD (years)                           735 non-null object
STDs                                  747 non-null object
STDs (number)                         747 non-null object
STDs:condylomatosis                   747 non-null object
STDs:cervical condylomatosis          747 non-null object
STDs:vaginal condylomatosis           747 non-null object
STDs:vulvo-perineal condylomatosis    747 non-null object
STDs:syphilis                         747 non-null object
STDs:pelvic inflammatory disease      747 non-null object
STDs:genital herpes                   747 non-null object
STDs:molluscum contagiosum            747 non-null object
STDs:AIDS                             747 non-null object
STDs:HIV                              747 non-null object
STDs:Hepatitis B                      747 non-null object
STDs:HPV                              747 non-null object
STDs: Number of diagnosis             851 non-null int64
Dx:Cancer                             851 non-null int64
Dx:CIN                                851 non-null int64
Dx:HPV                                851 non-null int64
Dx                                    851 non-null int64
Hinselmann                            851 non-null int64
Schiller                              851 non-null int64
Citology                              851 non-null int64
Biopsy                                851 non-null int64
dtypes: int64(10), object(24)
memory usage: 226.1+ KB

In [25]:
df = df[df['Num_of_pregnancies '].notnull()]

In [26]:
#lets count nan values in each  column
# Checking the percentage of missing values
round(100*(df.isnull().sum()/len(df.index)), 2)

Age                                    0.00
Number_of_sexual_partners              0.00
First_sexual_intercourse               0.00
Num_of_pregnancies                     0.00
Smokes                                 1.64
Smokes (years)                         1.64
Smo_pks/yr                             1.64
Hormonal Contraceptives               12.58
Hormonal Contraceptives (years)       12.58
IUD                                   12.83
IUD (years)                           12.83
STDs                                  11.95
STDs (number)                         11.95
STDs:condylomatosis                   11.95
STDs:cervical condylomatosis          11.95
STDs:vaginal condylomatosis           11.95
STDs:vulvo-perineal condylomatosis    11.95
STDs:syphilis                         11.95
STDs:pelvic inflammatory disease      11.95
STDs:genital herpes                   11.95
STDs:molluscum contagiosum            11.95
STDs:AIDS                             11.95
STDs:HIV                              11.95
STDs:Hepatitis B                      11.95
STDs:HPV                              11.95
STDs: Number of diagnosis              0.00
Dx:Cancer                              0.00
Dx:CIN                                 0.00
Dx:HPV                                 0.00
Dx                                     0.00
Hinselmann                             0.00
Schiller                               0.00
Citology                               0.00
Biopsy                                 0.00
dtype: float64

In [27]:
df=df.rename(columns={'Num of pregnancies':'Num_of_preg'})

In [28]:
df=df.rename(columns={'Smokes (years)':'sm_yr', 'Hormonal Contraceptives':'H_C','Hormonal Contraceptives (years)':'h_c_yr','STDs (number)':'STDs_n'})

In [29]:
df=df.rename(columns={'STDs:cervical condylomatosis':'TDs:cervical_condylomatosis', 'STDs:vaginal_condylomatosis':'STDs:vaginal_condylomatosis','STDs:vulvo-perineal condylomatosis':'STDs:vulvo_perineal_condylomatosis','STDs:pelvic inflammatory disease':'STDs:pelvic_inflammatory_disease'})

In [30]:
df=df.rename(columns={'STDs:genital herpes':'STDs:genital_herpes', 'STDs:molluscum contagiosum ':'STDs:molluscum_contagiosum ','STDs: Number of diagnosis ':'STDs:Number_of_diagnosis'})

In [31]:
#lets count nan values in each  column
# Checking the percentage of missing values
round(100*(df.isnull().sum()/len(df.index)), 2)

Age                                    0.00
Number_of_sexual_partners              0.00
First_sexual_intercourse               0.00
Num_of_pregnancies                     0.00
Smokes                                 1.64
sm_yr                                  1.64
Smo_pks/yr                             1.64
H_C                                   12.58
h_c_yr                                12.58
IUD                                   12.83
IUD (years)                           12.83
STDs                                  11.95
STDs_n                                11.95
STDs:condylomatosis                   11.95
TDs:cervical_condylomatosis           11.95
STDs:vaginal condylomatosis           11.95
STDs:vulvo_perineal_condylomatosis    11.95
STDs:syphilis                         11.95
STDs:pelvic_inflammatory_disease      11.95
STDs:genital_herpes                   11.95
STDs:molluscum contagiosum            11.95
STDs:AIDS                             11.95
STDs:HIV                              11.95
STDs:Hepatitis B                      11.95
STDs:HPV                              11.95
STDs: Number of diagnosis              0.00
Dx:Cancer                              0.00
Dx:CIN                                 0.00
Dx:HPV                                 0.00
Dx                                     0.00
Hinselmann                             0.00
Schiller                               0.00
Citology                               0.00
Biopsy                                 0.00
dtype: float64

In [32]:
df=df.rename(columns={'STDs:molluscum contagiosum':'STDs:molluscum_contagiosum','STDs: Number of diagnosis':'STDs:Number_of_diagnosis'})

In [33]:
#lets count nan values in each  column
# Checking the percentage of missing values
round(100*(df.isnull().sum()/len(df.index)), 2)

Age                                    0.00
Number_of_sexual_partners              0.00
First_sexual_intercourse               0.00
Num_of_pregnancies                     0.00
Smokes                                 1.64
sm_yr                                  1.64
Smo_pks/yr                             1.64
H_C                                   12.58
h_c_yr                                12.58
IUD                                   12.83
IUD (years)                           12.83
STDs                                  11.95
STDs_n                                11.95
STDs:condylomatosis                   11.95
TDs:cervical_condylomatosis           11.95
STDs:vaginal condylomatosis           11.95
STDs:vulvo_perineal_condylomatosis    11.95
STDs:syphilis                         11.95
STDs:pelvic_inflammatory_disease      11.95
STDs:genital_herpes                   11.95
STDs:molluscum_contagiosum            11.95
STDs:AIDS                             11.95
STDs:HIV                              11.95
STDs:Hepatitis B                      11.95
STDs:HPV                              11.95
STDs:Number_of_diagnosis               0.00
Dx:Cancer                              0.00
Dx:CIN                                 0.00
Dx:HPV                                 0.00
Dx                                     0.00
Hinselmann                             0.00
Schiller                               0.00
Citology                               0.00
Biopsy                                 0.00
dtype: float64

In [34]:
df = df[df['Smokes'].notnull()]

In [35]:
df = df[df['sm_yr'].notnull()]
df = df[df['Smo_pks/yr'].notnull()]

In [36]:
#lets count nan values in each  column
# Checking the percentage of missing values
round(100*(df.isnull().sum()/len(df.index)), 2)

Age                                    0.00
Number_of_sexual_partners              0.00
First_sexual_intercourse               0.00
Num_of_pregnancies                     0.00
Smokes                                 0.00
sm_yr                                  0.00
Smo_pks/yr                             0.00
H_C                                   12.15
h_c_yr                                12.15
IUD                                   12.53
IUD (years)                           12.53
STDs                                  11.76
STDs_n                                11.76
STDs:condylomatosis                   11.76
TDs:cervical_condylomatosis           11.76
STDs:vaginal condylomatosis           11.76
STDs:vulvo_perineal_condylomatosis    11.76
STDs:syphilis                         11.76
STDs:pelvic_inflammatory_disease      11.76
STDs:genital_herpes                   11.76
STDs:molluscum_contagiosum            11.76
STDs:AIDS                             11.76
STDs:HIV                              11.76
STDs:Hepatitis B                      11.76
STDs:HPV                              11.76
STDs:Number_of_diagnosis               0.00
Dx:Cancer                              0.00
Dx:CIN                                 0.00
Dx:HPV                                 0.00
Dx                                     0.00
Hinselmann                             0.00
Schiller                               0.00
Citology                               0.00
Biopsy                                 0.00
dtype: float64

In [37]:
df.reset_index(drop=True, inplace=True)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 782 entries, 0 to 781
Data columns (total 34 columns):
Age                                   782 non-null int64
Number_of_sexual_partners             782 non-null object
First_sexual_intercourse              782 non-null object
Num_of_pregnancies                    782 non-null object
Smokes                                782 non-null object
sm_yr                                 782 non-null object
Smo_pks/yr                            782 non-null object
H_C                                   687 non-null object
h_c_yr                                687 non-null object
IUD                                   684 non-null object
IUD (years)                           684 non-null object
STDs                                  690 non-null object
STDs_n                                690 non-null object
STDs:condylomatosis                   690 non-null object
TDs:cervical_condylomatosis           690 non-null object
STDs:vaginal condylomatosis           690 non-null object
STDs:vulvo_perineal_condylomatosis    690 non-null object
STDs:syphilis                         690 non-null object
STDs:pelvic_inflammatory_disease      690 non-null object
STDs:genital_herpes                   690 non-null object
STDs:molluscum_contagiosum            690 non-null object
STDs:AIDS                             690 non-null object
STDs:HIV                              690 non-null object
STDs:Hepatitis B                      690 non-null object
STDs:HPV                              690 non-null object
STDs:Number_of_diagnosis              782 non-null int64
Dx:Cancer                             782 non-null int64
Dx:CIN                                782 non-null int64
Dx:HPV                                782 non-null int64
Dx                                    782 non-null int64
Hinselmann                            782 non-null int64
Schiller                              782 non-null int64
Citology                              782 non-null int64
Biopsy                                782 non-null int64
dtypes: int64(10), object(24)
memory usage: 207.8+ KB

In [40]:
#lets count nan values in each  column
# Checking the percentage of missing values
round(100*(df.isnull().sum()/len(df.index)), 2)

Age                                    0.00
Number_of_sexual_partners              0.00
First_sexual_intercourse               0.00
Num_of_pregnancies                     0.00
Smokes                                 0.00
sm_yr                                  0.00
Smo_pks/yr                             0.00
H_C                                   12.15
h_c_yr                                12.15
IUD                                   12.53
IUD (years)                           12.53
STDs                                  11.76
STDs_n                                11.76
STDs:condylomatosis                   11.76
TDs:cervical_condylomatosis           11.76
STDs:vaginal condylomatosis           11.76
STDs:vulvo_perineal_condylomatosis    11.76
STDs:syphilis                         11.76
STDs:pelvic_inflammatory_disease      11.76
STDs:genital_herpes                   11.76
STDs:molluscum_contagiosum            11.76
STDs:AIDS                             11.76
STDs:HIV                              11.76
STDs:Hepatitis B                      11.76
STDs:HPV                              11.76
STDs:Number_of_diagnosis               0.00
Dx:Cancer                              0.00
Dx:CIN                                 0.00
Dx:HPV                                 0.00
Dx                                     0.00
Hinselmann                             0.00
Schiller                               0.00
Citology                               0.00
Biopsy                                 0.00
dtype: float64

In [41]:
df.H_C.value_counts()

1.0    443
0.0    244
Name: H_C, dtype: int64

In [42]:
df = df[df['STDs:HPV'].notnull()]

In [43]:
df = df[df['STDs:HPV'].notnull()]
df = df[df['STDs:Hepatitis B'].notnull()]
df = df[df['STDs:HIV'].notnull()]
df = df[df['STDs:AIDS'].notnull()]
df = df[df['STDs:molluscum_contagiosum'].notnull()]
df = df[df['STDs:genital_herpes'].notnull()]
df = df[df['STDs:pelvic_inflammatory_disease'].notnull()]
df = df[df['STDs:syphilis'].notnull()]
df = df[df['STDs:vulvo_perineal_condylomatosis'].notnull()]
df = df[df['STDs:vaginal condylomatosis'].notnull()]
df = df[df['TDs:cervical_condylomatosis'].notnull()]
df = df[df['STDs:condylomatosis'].notnull()]

In [44]:
#lets count nan values in each  column
# Checking the percentage of missing values
round(100*(df.isnull().sum()/len(df.index)), 2)

Age                                   0.00
Number_of_sexual_partners             0.00
First_sexual_intercourse              0.00
Num_of_pregnancies                    0.00
Smokes                                0.00
sm_yr                                 0.00
Smo_pks/yr                            0.00
H_C                                   1.45
h_c_yr                                1.45
IUD                                   1.45
IUD (years)                           1.45
STDs                                  0.00
STDs_n                                0.00
STDs:condylomatosis                   0.00
TDs:cervical_condylomatosis           0.00
STDs:vaginal condylomatosis           0.00
STDs:vulvo_perineal_condylomatosis    0.00
STDs:syphilis                         0.00
STDs:pelvic_inflammatory_disease      0.00
STDs:genital_herpes                   0.00
STDs:molluscum_contagiosum            0.00
STDs:AIDS                             0.00
STDs:HIV                              0.00
STDs:Hepatitis B                      0.00
STDs:HPV                              0.00
STDs:Number_of_diagnosis              0.00
Dx:Cancer                             0.00
Dx:CIN                                0.00
Dx:HPV                                0.00
Dx                                    0.00
Hinselmann                            0.00
Schiller                              0.00
Citology                              0.00
Biopsy                                0.00
dtype: float64

In [45]:
df = df[df['H_C'].notnull()]
df = df[df['h_c_yr'].notnull()]
df = df[df['IUD (years)'].notnull()]

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 679 entries, 0 to 781
Data columns (total 34 columns):
Age                                   679 non-null int64
Number_of_sexual_partners             679 non-null object
First_sexual_intercourse              679 non-null object
Num_of_pregnancies                    679 non-null object
Smokes                                679 non-null object
sm_yr                                 679 non-null object
Smo_pks/yr                            679 non-null object
H_C                                   679 non-null object
h_c_yr                                679 non-null object
IUD                                   679 non-null object
IUD (years)                           679 non-null object
STDs                                  679 non-null object
STDs_n                                679 non-null object
STDs:condylomatosis                   679 non-null object
TDs:cervical_condylomatosis           679 non-null object
STDs:vaginal condylomatosis           679 non-null object
STDs:vulvo_perineal_condylomatosis    679 non-null object
STDs:syphilis                         679 non-null object
STDs:pelvic_inflammatory_disease      679 non-null object
STDs:genital_herpes                   679 non-null object
STDs:molluscum_contagiosum            679 non-null object
STDs:AIDS                             679 non-null object
STDs:HIV                              679 non-null object
STDs:Hepatitis B                      679 non-null object
STDs:HPV                              679 non-null object
STDs:Number_of_diagnosis              679 non-null int64
Dx:Cancer                             679 non-null int64
Dx:CIN                                679 non-null int64
Dx:HPV                                679 non-null int64
Dx                                    679 non-null int64
Hinselmann                            679 non-null int64
Schiller                              679 non-null int64
Citology                              679 non-null int64
Biopsy                                679 non-null int64
dtypes: int64(10), object(24)
memory usage: 185.7+ KB

In [47]:
df=df.rename(columns={'IUD (years)':'IUD_yr','TDs:cervical_condylomatosis':'STDs:cervical_condylomatosis'})

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 679 entries, 0 to 781
Data columns (total 34 columns):
Age                                   679 non-null int64
Number_of_sexual_partners             679 non-null object
First_sexual_intercourse              679 non-null object
Num_of_pregnancies                    679 non-null object
Smokes                                679 non-null object
sm_yr                                 679 non-null object
Smo_pks/yr                            679 non-null object
H_C                                   679 non-null object
h_c_yr                                679 non-null object
IUD                                   679 non-null object
IUD_yr                                679 non-null object
STDs                                  679 non-null object
STDs_n                                679 non-null object
STDs:condylomatosis                   679 non-null object
STDs:cervical_condylomatosis          679 non-null object
STDs:vaginal condylomatosis           679 non-null object
STDs:vulvo_perineal_condylomatosis    679 non-null object
STDs:syphilis                         679 non-null object
STDs:pelvic_inflammatory_disease      679 non-null object
STDs:genital_herpes                   679 non-null object
STDs:molluscum_contagiosum            679 non-null object
STDs:AIDS                             679 non-null object
STDs:HIV                              679 non-null object
STDs:Hepatitis B                      679 non-null object
STDs:HPV                              679 non-null object
STDs:Number_of_diagnosis              679 non-null int64
Dx:Cancer                             679 non-null int64
Dx:CIN                                679 non-null int64
Dx:HPV                                679 non-null int64
Dx                                    679 non-null int64
Hinselmann                            679 non-null int64
Schiller                              679 non-null int64
Citology                              679 non-null int64
Biopsy                                679 non-null int64
dtypes: int64(10), object(24)
memory usage: 185.7+ KB

In [49]:
d_nc = df.select_dtypes(include=['int64'])
d_nc.head()

,Age,STDs:Number_of_diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,0,0,0,0,0,0,0,0,0
1,15,0,0,0,0,0,0,0,0,0
2,52,0,1,0,1,0,0,0,0,0
3,46,0,0,0,0,0,0,0,0,0
4,42,0,0,0,0,0,0,0,0,0

In [50]:
d_o = df.select_dtypes(include=['object'])
d_o.head()

,Number_of_sexual_partners,First_sexual_intercourse,Num_of_pregnancies,Smokes,sm_yr,Smo_pks/yr,H_C,h_c_yr,IUD,IUD_yr,...,STDs:vaginal condylomatosis,STDs:vulvo_perineal_condylomatosis,STDs:syphilis,STDs:pelvic_inflammatory_disease,STDs:genital_herpes,STDs:molluscum_contagiosum,STDs:AIDS,STDs:HIV,STDs:Hepatitis B,STDs:HPV
0,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3.0,23.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [51]:
list_c=list(d_o.columns)

In [52]:
list_c

['Number_of_sexual_partners',
 'First_sexual_intercourse',
 'Num_of_pregnancies ',
 'Smokes',
 'sm_yr',
 'Smo_pks/yr',
 'H_C',
 'h_c_yr',
 'IUD',
 'IUD_yr',
 'STDs',
 'STDs_n',
 'STDs:condylomatosis',
 'STDs:cervical_condylomatosis',
 'STDs:vaginal condylomatosis',
 'STDs:vulvo_perineal_condylomatosis',
 'STDs:syphilis',
 'STDs:pelvic_inflammatory_disease',
 'STDs:genital_herpes',
 'STDs:molluscum_contagiosum',
 'STDs:AIDS',
 'STDs:HIV',
 'STDs:Hepatitis B',
 'STDs:HPV']

In [54]:
df=df.rename(columns={'STDs:HPV':'STDs_HPV','STDs:Hepatitis B':'STDs_HepatitisB'})

In [55]:
df=df.rename(columns={'STDs:HIV':'STDs_HIV','STDs:AIDS':'STDs_AIDS','STDs:molluscum_contagiosum':'STDs_molluscum_contagiosum'})

In [56]:
for i in df.columns:
    
    i = i.lower().strip().replace(':',  '_')

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 679 entries, 0 to 781
Data columns (total 34 columns):
Age                                   679 non-null int64
Number_of_sexual_partners             679 non-null object
First_sexual_intercourse              679 non-null object
Num_of_pregnancies                    679 non-null object
Smokes                                679 non-null object
sm_yr                                 679 non-null object
Smo_pks/yr                            679 non-null object
H_C                                   679 non-null object
h_c_yr                                679 non-null object
IUD                                   679 non-null object
IUD_yr                                679 non-null object
STDs                                  679 non-null object
STDs_n                                679 non-null object
STDs:condylomatosis                   679 non-null object
STDs:cervical_condylomatosis          679 non-null object
STDs:vaginal condylomatosis           679 non-null object
STDs:vulvo_perineal_condylomatosis    679 non-null object
STDs:syphilis                         679 non-null object
STDs:pelvic_inflammatory_disease      679 non-null object
STDs:genital_herpes                   679 non-null object
STDs_molluscum_contagiosum            679 non-null object
STDs_AIDS                             679 non-null object
STDs_HIV                              679 non-null object
STDs_HepatitisB                       679 non-null object
STDs_HPV                              679 non-null object
STDs:Number_of_diagnosis              679 non-null int64
Dx:Cancer                             679 non-null int64
Dx:CIN                                679 non-null int64
Dx:HPV                                679 non-null int64
Dx                                    679 non-null int64
Hinselmann                            679 non-null int64
Schiller                              679 non-null int64
Citology                              679 non-null int64
Biopsy                                679 non-null int64
dtypes: int64(10), object(24)
memory usage: 185.7+ KB

In [58]:
df.columns = df.columns.str.replace(r"[:]", "_")

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 679 entries, 0 to 781
Data columns (total 34 columns):
Age                                   679 non-null int64
Number_of_sexual_partners             679 non-null object
First_sexual_intercourse              679 non-null object
Num_of_pregnancies                    679 non-null object
Smokes                                679 non-null object
sm_yr                                 679 non-null object
Smo_pks/yr                            679 non-null object
H_C                                   679 non-null object
h_c_yr                                679 non-null object
IUD                                   679 non-null object
IUD_yr                                679 non-null object
STDs                                  679 non-null object
STDs_n                                679 non-null object
STDs_condylomatosis                   679 non-null object
STDs_cervical_condylomatosis          679 non-null object
STDs_vaginal condylomatosis           679 non-null object
STDs_vulvo_perineal_condylomatosis    679 non-null object
STDs_syphilis                         679 non-null object
STDs_pelvic_inflammatory_disease      679 non-null object
STDs_genital_herpes                   679 non-null object
STDs_molluscum_contagiosum            679 non-null object
STDs_AIDS                             679 non-null object
STDs_HIV                              679 non-null object
STDs_HepatitisB                       679 non-null object
STDs_HPV                              679 non-null object
STDs_Number_of_diagnosis              679 non-null int64
Dx_Cancer                             679 non-null int64
Dx_CIN                                679 non-null int64
Dx_HPV                                679 non-null int64
Dx                                    679 non-null int64
Hinselmann                            679 non-null int64
Schiller                              679 non-null int64
Citology                              679 non-null int64
Biopsy                                679 non-null int64
dtypes: int64(10), object(24)
memory usage: 185.7+ KB

In [60]:
d_o2 = df.select_dtypes(include=['object'])
d_o2.head()

,Number_of_sexual_partners,First_sexual_intercourse,Num_of_pregnancies,Smokes,sm_yr,Smo_pks/yr,H_C,h_c_yr,IUD,IUD_yr,...,STDs_vaginal condylomatosis,STDs_vulvo_perineal_condylomatosis,STDs_syphilis,STDs_pelvic_inflammatory_disease,STDs_genital_herpes,STDs_molluscum_contagiosum,STDs_AIDS,STDs_HIV,STDs_HepatitisB,STDs_HPV
0,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,3.0,23.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [61]:
info.c=pd.to_numeric(info.d_o2, errors='coerce')

NameError: name 'info' is not defined

In [63]:
for a in d_o2.columns:
    d_o2[a] = pd.to_numeric(d_o2[a])
    
#df["a"] = pd.to_numeric(df["a"])

In [64]:
d_o2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 679 entries, 0 to 781
Data columns (total 24 columns):
Number_of_sexual_partners             679 non-null float64
First_sexual_intercourse              679 non-null float64
Num_of_pregnancies                    679 non-null float64
Smokes                                679 non-null float64
sm_yr                                 679 non-null float64
Smo_pks/yr                            679 non-null float64
H_C                                   679 non-null float64
h_c_yr                                679 non-null float64
IUD                                   679 non-null float64
IUD_yr                                679 non-null float64
STDs                                  679 non-null float64
STDs_n                                679 non-null float64
STDs_condylomatosis                   679 non-null float64
STDs_cervical_condylomatosis          679 non-null float64
STDs_vaginal condylomatosis           679 non-null float64
STDs_vulvo_perineal_condylomatosis    679 non-null float64
STDs_syphilis                         679 non-null float64
STDs_pelvic_inflammatory_disease      679 non-null float64
STDs_genital_herpes                   679 non-null float64
STDs_molluscum_contagiosum            679 non-null float64
STDs_AIDS                             679 non-null float64
STDs_HIV                              679 non-null float64
STDs_HepatitisB                       679 non-null float64
STDs_HPV                              679 non-null float64
dtypes: float64(24)
memory usage: 132.6 KB

In [65]:
l22=list(d_o2.columns)

In [66]:
df.drop(l22, axis=1, inplace=True)

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 679 entries, 0 to 781
Data columns (total 10 columns):
Age                         679 non-null int64
STDs_Number_of_diagnosis    679 non-null int64
Dx_Cancer                   679 non-null int64
Dx_CIN                      679 non-null int64
Dx_HPV                      679 non-null int64
Dx                          679 non-null int64
Hinselmann                  679 non-null int64
Schiller                    679 non-null int64
Citology                    679 non-null int64
Biopsy                      679 non-null int64
dtypes: int64(10)
memory usage: 58.4 KB

In [68]:
from sklearn.preprocessing import MinMaxScaler

In [69]:
df22 = df.select_dtypes(include=['int64'])
df22.head()

,Age,STDs_Number_of_diagnosis,Dx_Cancer,Dx_CIN,Dx_HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,0,0,0,0,0,0,0,0,0
1,15,0,0,0,0,0,0,0,0,0
2,52,0,1,0,1,0,0,0,0,0
3,46,0,0,0,0,0,0,0,0,0
4,42,0,0,0,0,0,0,0,0,0

In [70]:
df22.drop('Biopsy', axis=1, inplace=True)

In [71]:
from sklearn.preprocessing import MinMaxScaler

In [72]:
scaler = MinMaxScaler()

In [73]:
l123=list(df22.columns)

In [74]:
df22[l123] = scaler.fit_transform(df22[l123])

In [75]:
df22.head()

,Age,STDs_Number_of_diagnosis,Dx_Cancer,Dx_CIN,Dx_HPV,Dx,Hinselmann,Schiller,Citology
0,0.070423,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.028169,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.549296,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.464789,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.408451,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [76]:
df=df.drop(l123, axis=1, inplace=True)

In [80]:
df22

,Age,STDs_Number_of_diagnosis,Dx_Cancer,Dx_CIN,Dx_HPV,Dx,Hinselmann,Schiller,Citology
0,0.070423,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.028169,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.549296,0.000000,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,0.464789,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.408451,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.535211,0.000000,0.0,0.0,0.0,0.0,1.0,1.0,0.0
6,0.183099,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.450704,0.000000,1.0,0.0,1.0,1.0,0.0,0.0,0.0
8,0.436620,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.197183,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.450704,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.436620,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.422535,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.380282,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.394366,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.422535,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.422535,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.394366,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.380282,0.333333,0.0,0.0,0.0,0.0,0.0,1.0,1.0
19,0.380282,0.000000,1.0,0.0,1.0,0.0,1.0,1.0,0.0
20,0.380282,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,0.436620,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.366197,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.366197,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.338028,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0.338028,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0.394366,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,0.380282,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.338028,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,0.338028,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
752,0.408451,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
753,0.281690,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0
754,0.309859,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
755,0.281690,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
756,0.295775,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
757,0.309859,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
758,0.380282,0.333333,0.0,0.0,0.0,0.0,0.0,0.0,0.0
759,0.239437,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
760,0.239437,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
761,0.154930,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
762,0.309859,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
763,0.253521,0.000000,1.0,0.0,0.0,1.0,0.0,0.0,0.0
764,0.154930,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
765,0.140845,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
766,0.323944,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
767,0.239437,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
768,0.183099,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
769,0.084507,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
770,0.309859,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
771,0.239437,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
772,0.253521,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
773,0.267606,0.000000,1.0,0.0,1.0,0.0,0.0,0.0,0.0
774,0.084507,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
775,0.140845,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
776,0.422535,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
777,0.295775,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
778,0.267606,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
779,0.169014,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0
780,0.281690,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
781,0.225352,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0